import numpy as np
from numpy.lib.stride_tricks import as_strided
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
print("Broadcasting:\n", a + b)
arr = np.array([1, 2, 3, 4])
print("Vectorization:", arr ** 2)
data = np.array([10, 20, 30, 40, 50])
print("Fancy Indexing:", data[[0, 2, 4]])
print("Boolean Masking:", data[data > 25])
matrix = np.arange(12).reshape(3, 4)
print("Reshaped:\n", matrix)
a1 = np.array([1, 2])
a2 = np.array([3, 4])
print("Vstack:\n", np.vstack((a1, a2)))
print("Hstack:\n", np.hstack((a1, a2)))
arr_split = np.array([1, 2, 3, 4, 5, 6])
print("Split:", np.array_split(arr_split, 3))
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("Dot Product:\n", np.dot(mat1, mat2))
arr_stats = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(arr_stats))
print("Std:", np.std(arr_stats))
print("Random:\n", np.random.rand(3, 3))
arr_stride = np.array([[1, 2, 3],
                       [4, 5, 6]], dtype=np.int32)
print("Strides:", arr_stride.strides)
x = np.arange(6, dtype=np.int32)
print("Strided View:\n", as_strided(x, shape=(3, 2), strides=(4, 4)))
a = np.arange(12).reshape(3, 4)
print("C_CONTIGUOUS:", a.flags['C_CONTIGUOUS'])
b = a.T
print("After Transpose:", b.flags['C_CONTIGUOUS'])
c = np.ascontiguousarray(b)
print("Fixed:", c.flags['C_CONTIGUOUS'])
arr1 = np.arange(1000, dtype=np.int64)
arr2 = arr1.astype(np.int32)
print("Memory:", arr1.nbytes, arr2.nbytes)
original = np.arange(10)
view = original[2:8]
view[0] = 999
print("View Effect:", original)
arr3 = np.array([1, 2, 3, 4])
arr3 *= 2
print("In-place:", arr3)
print("Bytes Used:", arr3.nbytes)
